38 fix crash first launch
Towich/CosmicIntrigue pull request #39
Opened 2024-07-21 17:49 UTC by Kaz1deX

2024-07-21 20:57 UTC, Towich requested changes
Создать класс PermissionsManager

2024-07-21 21:10 UTC, Towich commented on app/src/main/java/com/towich/cosmicintrigue/application/activity/MenuActivity.kt
> +    }
Вынести в отдельный класс

2024-07-21 21:10 UTC, Towich commented on app/src/main/java/com/towich/cosmicintrigue/ui/fragment/RoleFragment.kt
> +        )
Вынести в отдельный класс

2024-07-21 21:12 UTC, Kaz1deX commented on app/src/main/java/com/towich/cosmicintrigue/application/activity/MenuActivity.kt
> +    }
Будет сделано, босс

2024-07-22 19:04 UTC, Towich approved these changes
всё классно, алертДиалог бомбовый))

2024-07-22 19:09 UTC, merged

2024-07-22 19:19 UTC, Towich commented on app/src/main/java/com/towich/cosmicintrigue/data/source/PermissionsManager.kt
> +        val permissionsArray = mutableListOf(
Можно тут назвать "permissionsList", тут ведь у нас лист)